"""Module for the Game Settings"""

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
FPS = 60


# Player Settings
PLAYER_SPEED = 100
PLAYER_JUMP = 200
PLAYER_SCALE = 2

# Tile Settings
TILE_SIZE = 16
TILE_HEIGHT = 16
TILE_WIDTH = 16
TILE_SCALE = (3, 4)

# Pipe Settings
PIPE_WIDTH = 32
PIPE_SCALE = (3, 4)
PIPE_HEIGHT = 48
